MembershipRules     = _{ SOI ~ Segment ~ EOI }



Segment     = { ( ( Node | Brackets ) ~ Comparator )* ~ ( Node | Brackets ) }



Brackets    = _{ "(" ~ Segment ~ ")" }

// Nodes and Rule Conditions
Node            = _{ SingleNode | ArrayNode }
SingleNode       = { Property ~ SingleOp ~ Value }
ArrayNode    = { Property ~ ArrayOp ~ Array }


Property        = @{ Object ~ "." ~ clean_inner }
// Property        = @{ "user." ~ clean_inner }
    clean_inner     = @{ clean_char* }
    clean_char      = { !(WHITESPACE) ~ ANY }
Object = { ^"user" | ^"device" }


Value   = _{ boolean | number | string_outer | null }

    boolean = _{ True | False }
        True    = { ^"true"  | ^"\"true\""  }
        False   = { ^"false" | ^"\"false\"" }

    string_outer    = _{ "\"" ~ string ~ "\"" }
        string      = @{ string_char* }
        string_char = { !("\"" | "\\") ~ ANY }

    number  = { '0'..'9' }
    null    = { ^"null" | ^"$null" }

Array   = {
    "[" ~ "]" |
    "[" ~ Value ~ ("," ~ Value)* ~ "]"
}



WHITESPACE = _{ " " | "\t" | "\r" | "\n" }



//
// OPERATORS
//
// https://learn.microsoft.com/en-gb/entra/identity/users/groups-dynamic-membership
//

// "Comparator" is an Operator
Comparator  = _{ And | Or }
And     = @{ "-"? ~ ^"and" }
Or      = @{ "-"? ~ ^"or"  }

// Functional Operator Categories
SingleOp        = { Contains | EndsWith | Equals | NotEndsWith | NotContains | NotEquals | NotStartsWith | StartsWith }
ArrayOp         = { In | NotIn }
ComparativeOp   = { GreaterThanOrEqual | LessThanOrEqual }
RegExOp         = { Match | NotMatch }
MultiValueOp    = { All | Any }
MathOp          = { Add | Subtract }

// All Operators
Add                 = @{ "-"? ~ ^"plus" }
All                 = @{ "-"? ~ ^"all" }
Any                 = @{ "-"? ~ ^"any" }
Contains            = @{ "-"? ~ ^"contains" }
EndsWith            = @{ "-"? ~ ^"endsWith" }
Equals              = @{ "-"? ~ ^"eq" }
GreaterThanOrEqual  = @{ "-"? ~ ^"ge" }
In                  = @{ "-"? ~ ^"in" }
LessThanOrEqual     = @{ "-"? ~ ^"le" }
Match               = @{ "-"? ~ ^"match" }
NotContains         = @{ "-"? ~ ^"notContains" }
NotEndsWith         = @{ "-"? ~ ^"notEndsWith" }
NotEquals           = @{ "-"? ~ ^"ne" }
NotIn               = @{ "-"? ~ ^"notIn"  }
NotMatch            = @{ "-"? ~ ^"notMatch"  }
NotStartsWith       = @{ "-"? ~ ^"notStartsWith" }
StartsWith          = @{ "-"? ~ ^"startsWith" }
Subtract            = @{ "-"? ~ ^"minus" }