MembershipRules     = _{ SOI ~ Segment ~ EOI }



Segment     = { ( ( Brackets | Node | RemovalNode ) ~ Comparator )* ~ ( Brackets | Node | RemovalNode ) }



Brackets    = _{ "(" ~ Segment ~ ")" }

// Nodes and Rule Conditions
Node = { Property ~ ( Operator | NotOperator ) ~ ( Value | Array ) }
// Node            = _{ SingleNode | ArrayNode | RemovalNode}
// SingleNode       = { Property ~ SingleOp ~ Value }
// ArrayNode    = { Property ~ ArrayOp ~ Array }
RemovalNode  = {
    ( Blank | Property ) ~ 
    ( Blank | Operator | NotOperator ) ~ 
    ( Blank | Value | Array )
}


Property        = @{ Object ~ "." ~ Variable }
    Object              = { ^"user" | ^"device" }
    Variable            = @{ VariableCharacter* }
    VariableCharacter   = { !(WHITESPACE) ~ ANY }


Value   = _{ Boolean | Number | StringWrapper | Null | "(" ~ Value ~ ")"}
Blank   = { "*" }
    
    Boolean = _{ True | False }
        True    = { ^"true"  | ^"\"true\""  }
        False   = { ^"false" | ^"\"false\"" }

    StringWrapper    = _{ "\"" ~ String ~ "\"" }
        String      = @{ StringCharacter* }
        StringCharacter = { !("\"" | "\\") ~ ANY }

    Number  = { '0'..'9' }
    Null    = @{ "$"? ~ ^"null" }

Array   = {
    "[" ~ "]" |
    "[" ~ Value ~ ("," ~ Value)* ~ "]"
}



WHITESPACE = _{ " " | "\t" | "\r" | "\n" }



//
// OPERATORS
//
// https://learn.microsoft.com/en-gb/entra/identity/users/groups-dynamic-membership
//

OpPrefix    = _{ "-" }

// "Comparator" is an Operator
Comparator  = _{ And | Or }
And     = @{ OpPrefix? ~ ^"and" }
Or      = @{ OpPrefix? ~ ^"or"  }

Operator = ${
    OpPrefix? ~ 
    (
        SingleOp
        | ArrayOp
        | ComparativeOp
        | RegExOp
        | MultiValueOp 
        | MathOp
    )
}
NotOperator = { Not? ~ Operator }

// Functional Operator Categories
SingleOp        = _{ Contains | EndsWith | Equals | NotEndsWith | NotContains | NotEquals | NotStartsWith | StartsWith }
ArrayOp         = _{ In | NotIn }
ComparativeOp   = _{ GreaterThanOrEqual | LessThanOrEqual }
RegExOp         = _{ Match | NotMatch }
MultiValueOp    = _{ All | Any }
MathOp          = _{ Add | Subtract }

// All Operators
Add                 = @{ OpPrefix? ~ ^"plus" }
All                 = @{ OpPrefix? ~ ^"all" }
Any                 = @{ OpPrefix? ~ ^"any" }
Contains            = @{ OpPrefix? ~ ^"contains" }
EndsWith            = @{ OpPrefix? ~ ^"endsWith" }
Equals              = @{ OpPrefix? ~ ^"eq" }
GreaterThanOrEqual  = @{ OpPrefix? ~ ^"ge" }
In                  = @{ OpPrefix? ~ ^"in" }
LessThanOrEqual     = @{ OpPrefix? ~ ^"le" }
Match               = @{ OpPrefix? ~ ^"match" }
Not                 = @{ OpPrefix? ~ ^"not" }
NotContains         = @{ OpPrefix? ~ ^"notContains" }
NotEndsWith         = @{ OpPrefix? ~ ^"notEndsWith" }
NotEquals           = @{ OpPrefix? ~ ^"ne" }
NotIn               = @{ OpPrefix? ~ ^"notIn"  }
NotMatch            = @{ OpPrefix? ~ ^"notMatch"  }
NotStartsWith       = @{ OpPrefix? ~ ^"notStartsWith" }
StartsWith          = @{ OpPrefix? ~ ^"startsWith" }
Subtract            = @{ OpPrefix? ~ ^"minus" }