MembershipRules = _{ SOI ~ Segment ~ EOI }

Segment = { ( ( Rule | Brackets ) ~ Comparator )* ~ ( Rule | Brackets ) }

Rule = { Object ~ Operator ~ Value }

Brackets = _{ "(" ~ Segment ~ ")" }

Value = _{ string | array | boolean | null }
    string  = ${ "\"" ~ string_inner ~ "\"" }
        string_inner   = @{ string_char* }
        string_char    = { !("\"" | "\\") ~ ANY }
    array   = {
        "[" ~ "]" |
        "[" ~ Value ~ ("," ~ Value)* ~ "]"
    }
    boolean = { ^"true" | ^"false" }
    null    = { ^"null" }

Comparator  = { ^"and" | ^"or" }
Operator    = ${ "-" ~ clean_inner }
Object      = ${ "user." ~ clean_inner }
    clean_inner   = @{ clean_char* }
    clean_char    = { !(WHITESPACE) ~ ANY }

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
